import { FEATURE_FIELDS } from './feature-fields.js'

// Command ID definitions
export const COMMAND_ID_MAP = {
  0x0001: { name: 'Get Command',                  dir: 'App → Device', category: 'Device Info' },
  0x0002: { name: 'Set Command',                  dir: 'App → Device', category: 'Device Info' },
  0x0003: { name: 'Notification',                 dir: 'Device → App', category: 'Device Info' },
  0x0004: { name: 'Notification',                 dir: 'App → Device', category: 'Device Info' },
  0x0101: { name: 'Start OTA',                    dir: 'App → Device', category: 'OTA' },
  0x0102: { name: 'Send OTA Data',                dir: 'App → Device', category: 'OTA' },
  0x0103: { name: 'Stop OTA',                     dir: 'App → Device', category: 'OTA' },
  0x0104: { name: 'OTA Notification',             dir: 'Device → App', category: 'OTA' },
  0x0201: { name: 'Get Device Analytics Data',    dir: 'App → Device', category: 'Analytics' },
  0x02FF: { name: 'Clean Device Analytics Data',  dir: 'App → Device', category: 'Analytics' },
}

// Feature ID definitions (Common + OTA groups)
export const FEATURE_ID_MAP = {
  // ── Common Group [0x0000, 0x0AFF] ──────────────────────────────────────────
  0x0000: { name: 'Unsupported Feature ID List',                           perm: 'N' },
  0x0001: { name: 'MTU',                                                   perm: 'R',     valueSize: 2 },
  0x0002: { name: 'App Alive Heartbeat Request from Device',               perm: 'W',     valueSize: 0 },
  0x0003: { name: 'Continuous Packets Minimal Transmission Interval (ms)', perm: 'R',     valueSize: 2 },
  0x0004: { name: 'Product ID',                                            perm: 'R',     valueSize: 2 },
  0x0005: { name: 'Color ID',                                              perm: 'R',     valueSize: 1 },
  0x0006: { name: 'Device Name',                                           perm: 'R/W',   maxSize: 32 },
  0x0007: { name: 'Host Name CRC16',                                       perm: 'R/W',   valueSize: 2 },
  0x0008: { name: 'Left/Primary Device Serial Number',                     perm: 'R',     maxSize: 64 },
  0x0009: { name: 'Right/Secondary Device Serial Number',                  perm: 'R',     maxSize: 64 },
  0x000A: { name: 'Device BT MAC Address',                                 perm: 'R',     valueSize: 6 },
  0x000B: { name: 'Secondary Device BT MAC Address',                       perm: 'R',     valueSize: 6 },
  0x000C: { name: 'Firmware Version',                                      perm: 'R',     maxSize: 6 },
  0x000D: { name: 'Left/Primary Device Battery Status',                    perm: 'R/N',   valueSize: 1 },
  0x000E: { name: 'Right/Secondary Device Battery Status',                  perm: 'R/N',   valueSize: 1 },
  0x000F: { name: 'Factory Reset',                                         perm: 'W',     valueSize: 0 },
  0x0010: { name: 'BT Connection Status',                                  perm: 'R/N',   valueSize: 1 },
  0x0011: { name: 'Manual Power Off',                                       perm: 'W/N',   valueSize: 2 },
  0x0012: { name: 'Auto Power Off',                                        perm: 'R/W',   valueSize: 2 },
  0x0013: { name: 'Auto Standby (Deprecated)',                             perm: 'R/W',   valueSize: 2 },
  0x0014: { name: 'Game Chat Balance',                                     perm: 'R/W/N', valueSize: 1 },
  0x0015: { name: 'LR Balance',                                            perm: 'R/W/N', valueSize: 1 },
  0x0016: { name: 'Microphone Work Indicating LED Brightness',             perm: 'R/W',   valueSize: 1 },
  0x0017: { name: 'Battery Presence',                                      perm: 'R',     valueSize: 1 },
  0x0018: { name: 'ANC',                                                   perm: 'R/W/N', valueSize: 1 },
  0x0019: { name: 'Ambient Aware (AA)',                                    perm: 'R/W/N', valueSize: 1 },
  0x001A: { name: 'Talk Thru (TT)',                                        perm: 'R/W/N', valueSize: 1 },
  0x001B: { name: 'Adaptive ANC',                                          perm: 'R/W',   valueSize: 1 },
  0x001C: { name: 'True Adaptive ANC',                                     perm: 'R/W',   valueSize: 1 },
  0x001D: { name: 'Leakage Compensation',                                  perm: 'R/W',   valueSize: 1 },
  0x001E: { name: 'Ear Canal Compensation',                                perm: 'R/W',   valueSize: 1 },
  0x001F: { name: 'ANC Always On',                                         perm: 'R/W',   valueSize: 1 },
  0x0020: { name: 'Auto Compensation',                                     perm: 'R/W',   valueSize: 1 },
  0x0021: { name: 'Spatial Sound Mode',                                    perm: 'R/W',   valueSize: 1 },
  0x0022: { name: 'Spatial Sound Scene',                                   perm: 'R/W',   valueSize: 1 },
  0x0023: { name: 'Sidetone',                                              perm: 'R/W',   valueSize: 1 },
  0x0024: { name: 'Low EQ Compensation',                                   perm: 'R/W',   valueSize: 1 },
  0x0025: { name: 'Max Volume Limit (Legacy)',                             perm: 'R/W',   valueSize: 1 },
  0x0026: { name: 'Noise Suppression',                                     perm: 'R/W',   valueSize: 1 },
  0x0027: { name: 'Audio Limiter (Sound Level Optimizer)',                 perm: 'R/W',   valueSize: 1 },
  0x0028: { name: 'Hi-Res',                                                perm: 'R/W',   valueSize: 1 },
  0x0029: { name: 'Sound Effect (Sound Setting)',                          perm: 'R/W',   valueSize: 1 },
  0x002A: { name: 'Auto Play/Pause Enable',                               perm: 'R/W',   valueSize: 1 },
  0x002B: { name: 'Smart Talk',                                            perm: 'R/W',   valueSize: 1 },
  0x002C: { name: 'Charging Pin/Port Detect',                             perm: 'R',     valueSize: 1 },
  0x002D: { name: 'Spatial Sound Recenter',                               perm: 'W',     valueSize: 1 },
  0x002E: { name: 'BLE Paired Status',                                    perm: 'N',     valueSize: 1 },
  0x002F: { name: 'Host Type',                                             perm: 'W',     valueSize: 1 },
  0x0030: { name: 'Text Message Notification Setting',                     perm: 'W',     valueSize: 151 },
  0x0031: { name: 'Sync Time',                                             perm: 'R/W',   valueSize: 16 },
  0x0032: { name: 'Text Message Notification Remove All',                  perm: 'W',     valueSize: 0 },
  0x0033: { name: 'Host BLE MAC Address',                                  perm: 'R',     valueSize: 7 },
  0x0034: { name: 'Headphone and Case Connection Status',                  perm: 'R',     valueSize: 1 },
  0x0035: { name: 'Headphone and Dongle Connection Status',                perm: 'R',     valueSize: 1 },
  0x0036: { name: 'Headphone and Smart Transmitter Connection Status',     perm: 'R',     valueSize: 1 },
  0x0037: { name: 'Water Ejection',                                        perm: 'R/W',   valueSize: 1 },
  0x0038: { name: 'Smart Transmitter Serial Number',                       perm: 'R',     maxSize: 64 },
  0x0039: { name: 'Host Name Paired to BT Device',                        perm: 'R/N' },
  0x003A: { name: 'Authenticate Mode',                                     perm: 'W',     valueSize: 1 },
  0x003B: { name: 'Authenticate Button is Pressed',                        perm: 'N',     valueSize: 0 },
  0x003C: { name: 'Full Firmware Version',                                 perm: 'R',     maxSize: 128 },
  0x003D: { name: 'Audio Signal Detect',                                   perm: 'R',     valueSize: 1 },
  0x003E: { name: 'Authenticate Device',                                   perm: 'W/N' },
  0x003F: { name: 'Dongle State',                                          perm: 'R',     valueSize: 1 },
  0x0040: { name: 'Spatial Sound Availability',                            perm: 'R',     valueSize: 1 },
  0x0041: { name: 'Message CRC16',                                         perm: 'R/W',   valueSize: 2 },
  0x0042: { name: 'Secondary Device Factory Reset',                        perm: 'W',     valueSize: 0 },
  0x0043: { name: 'App Active Heartbeat Initiate Sending from App',        perm: 'N',     valueSize: 0 },
  0x0044: { name: 'Custom Data',                                           perm: 'R/W' },
  0x0045: { name: 'Primary Device Power State',                            perm: 'R',     valueSize: 1 },
  0x0046: { name: 'Device BT MAC Address CRC16',                           perm: 'R',     valueSize: 2 },
  0x0047: { name: 'Secondary Device BT MAC Address CRC16',                 perm: 'R',     valueSize: 2 },
  0x0048: { name: 'Smart Transmitter Audio Streaming Supported',           perm: 'W',     valueSize: 1 },
  0x0049: { name: 'Ambient Sound Control',                                 perm: 'R/W',   valueSize: 1 },
  0x004A: { name: 'Authentication Algorithm',                              perm: 'W',     valueSize: 1 },
  0x004B: { name: 'Advanced Authenticate Device',                          perm: 'W' },
  0x004C: { name: 'Individual Max Volume Limit Query',                     perm: 'Q',     valueSize: 1 },
  0x004D: { name: 'Individual Max Volume Limit',                           perm: 'W/N',   valueSize: 2 },
  0x004E: { name: 'Default Volume',                                        perm: 'R/W',   valueSize: 1 },
  0x004F: { name: 'Manual Power On',                                       perm: 'W/N',   valueSize: 0 },
  // ── OTA Group [0x0B00, 0x0B3F] ─────────────────────────────────────────────
  0x0B00: { name: 'OTA Device Internal MTU',                               perm: 'R',     valueSize: 2 },
  0x0B01: { name: 'OTA Continuous Packets Maximum Count',                  perm: 'R',     valueSize: 1 },
  0x0B02: { name: 'OTA MTU Between App and Device',                        perm: 'R',     valueSize: 2 },
  0x0B03: { name: 'OTA Continuous Packets Minimal Transmission Interval (ms)', perm: 'R', valueSize: 2 },
  0x0B04: { name: 'OTA Upgrade Components',                                perm: 'W',     valueSize: 1 },
  // ── AI Group [0x0B40, 0x0B7F] ──────────────────────────────────────────────
  0x0B40: { name: 'ChatGPT Dialog',                                        perm: '-',     valueSize: 1 },
  0x0B41: { name: 'ChatGPT Call Function Selection',                       perm: 'R/W',   valueSize: 1 },
  0x0B42: { name: 'ChatGPT Call Uplink Data',                              perm: '-',     valueSize: 1 },
  0x0B43: { name: 'ChatGPT Call Downlink Data',                            perm: '-',     valueSize: 1 },
  0x0B60: { name: 'Multi AI',                                              perm: 'R/W',   valueSize: 1 },
  // ── LE Audio Group [0x0B80, 0x0BBF] ────────────────────────────────────────
  0x0B80: { name: 'LE Audio Auracast Info',                                perm: 'R' },
  0x0B81: { name: 'LE Audio Auracast Scan',                                perm: 'W',     valueSize: 2 },
  0x0B82: { name: 'LE Audio Auracast Group Info',                          perm: '-',     valueSize: 41 },
  0x0B83: { name: 'LE Audio Auracast Group Select',                        perm: 'W' },
  0x0B84: { name: 'LE Audio Auracast Subgroup Info',                       perm: '-' },
  0x0B85: { name: 'LE Audio Auracast Subgroup Play',                       perm: 'W',     valueSize: 3 },
  0x0B86: { name: 'LE Audio Auracast Broadcast Status',                    perm: 'R/W',   valueSize: 1 },
  0x0B87: { name: 'LE Audio Auracast Broadcast High Quality',              perm: 'R/W',   valueSize: 1 },
  0x0B88: { name: 'LE Audio Auracast Broadcast Password',                  perm: 'R/W',   maxSize: 16 },
  0x0B89: { name: 'LE Audio Auracast Broadcast Address',                   perm: 'R/W',   valueSize: 6 },
  0x0B8A: { name: 'LE Audio Auracast Broadcast Name',                      perm: 'R/W' },
  0x0BA0: { name: 'LE Audio Unicast Status',                               perm: 'R/W',   valueSize: 1 },
  0x0BA1: { name: 'Active Audio Source',                                   perm: 'R/W',   valueSize: 1 },
  0x0BA2: { name: 'Audio Source Info',                                     perm: 'R' },
  0x0BA3: { name: 'Get Paired BT Device',                                  perm: 'R' },
  0x0BA4: { name: 'Operate Paired BT Device',                              perm: 'W',     valueSize: 7 },
  0x0BA5: { name: 'BT Pairing Mode',                                       perm: 'R/W',   valueSize: 2 },
  0x0BA6: { name: 'OneCast over LE Audio Pairing Mode',                    perm: 'R/W',   valueSize: 1 },
  // ── Mic Group [0x0C00, 0x0C3F] ─────────────────────────────────────────────
  0x0C00: { name: 'Mic Availability',                                      perm: 'R',     valueSize: 1 },
  0x0C01: { name: 'Mic Signal Strength',                                   perm: 'R',     valueSize: 1 },
  0x0C02: { name: 'Mic Real Time Voice Level',                             perm: 'R',     valueSize: 1 },
  0x0C03: { name: 'Mic Mute',                                              perm: 'R/W',   valueSize: 1 },
  0x0C04: { name: 'Mic Volume',                                            perm: 'R/W',   valueSize: 1 },
  0x0C05: { name: 'Mic Effect',                                            perm: 'R/W',   valueSize: 1 },
  0x0C06: { name: 'Mic Effect Test',                                       perm: 'R/W',   valueSize: 1 },
  0x0C07: { name: 'Mic Record Operation',                                  perm: 'W',     valueSize: 2 },
  0x0C08: { name: 'Mic Record Status',                                     perm: 'R',     valueSize: 1 },
  0x0C09: { name: 'Mic1 Echo',                                             perm: 'R/W',   valueSize: 1 },
  0x0C0A: { name: 'Mic1 Reverb',                                           perm: 'R/W',   valueSize: 1 },
  0x0C0B: { name: 'Mic1 Sensitivity in Level',                             perm: 'R/W',   valueSize: 1 },
  0x0C0C: { name: 'Mic1 Sensitivity in dB',                                perm: 'R/W',   valueSize: 4 },
  0x0C0D: { name: 'Mic2 Echo',                                             perm: 'R/W',   valueSize: 1 },
  0x0C0E: { name: 'Mic2 Reverb',                                           perm: 'R/W',   valueSize: 1 },
  0x0C0F: { name: 'Mic2 Sensitivity in Level',                             perm: 'R/W',   valueSize: 1 },
  0x0C10: { name: 'Mic2 Sensitivity in dB',                                perm: 'R/W',   valueSize: 4 },
  0x0C11: { name: 'Mic Polar Pattern',                                     perm: 'R/W',   valueSize: 1 },
  // ── Voice Prompt Group [0x0C40, 0x0C7F] ────────────────────────────────────
  0x0C40: { name: 'Voice Prompt Status',                                   perm: 'R/W',   valueSize: 1 },
  0x0C41: { name: 'Voice Prompt Language',                                 perm: 'R/W',   valueSize: 1 },
  0x0C42: { name: 'Voice Prompt File Version',                             perm: 'R',     valueSize: 3 },
  0x0C43: { name: 'Voice Prompt Volume',                                   perm: 'R/W',   valueSize: 1 },
  0x0C44: { name: 'Feedback Tone Volume',                                  perm: 'R/W',   valueSize: 1 },
  // ── PSAP Group [0x0C80, 0x0CAF] ────────────────────────────────────────────
  0x0C80: { name: 'PSAP Status',                                           perm: 'R/W',   valueSize: 1 },
  0x0C81: { name: 'PSAP Balance',                                          perm: 'R/W',   valueSize: 1 },
  0x0C82: { name: 'PSAP Total Gain Level',                                 perm: 'R/W',   valueSize: 1 },
  0x0C83: { name: 'PSAP Reduce Background Noise',                          perm: 'R/W',   valueSize: 1 },
  0x0C84: { name: 'PSAP Beamforming',                                      perm: 'R/W',   valueSize: 1 },
  // ── Sleep Group [0x0CB0, 0x0CFF] ───────────────────────────────────────────
  0x0CB0: { name: 'Sleep Active Status',                                   perm: 'R/W',   valueSize: 1 },
  0x0CB1: { name: 'Sleep Setting',                                         perm: 'R/W',   valueSize: 4 },
  0x0CB2: { name: 'Wake-up Setting',                                       perm: 'R/W',   valueSize: 4 },
  0x0CB3: { name: 'Sleep Count Down Setting',                              perm: 'R',     valueSize: 4 },
  0x0CB4: { name: 'Alarm Ring Tone',                                       perm: 'R/W',   valueSize: 1 },
  // ── EQ Group [0x0E00, 0x0EFF] ──────────────────────────────────────────────
  0x0E01: { name: 'EQ Info Query',                                         perm: 'Q',     valueSize: 1 },
  0x0E02: { name: 'EQ Info',                                               perm: 'W/N' },
  0x0E03: { name: 'EQ Sequence',                                           perm: 'R/W' },
  0x0E7E: { name: 'Get Design EQ Raw Data',                                perm: 'R' },
  0x0E7F: { name: 'EQ Curve',                                              perm: 'W' },
  0x0E80: { name: 'Dynamic EQ',                                            perm: 'R/W',   valueSize: 1 },
  0x0E81: { name: 'Custom EQ Count on App',                                perm: 'R/W',   valueSize: 2 },
  // ── Lighting Group [0x0D00, 0x0DFF] ────────────────────────────────────────
  0x0D00: { name: 'Lighting Status',                                       perm: 'R/W',   valueSize: 1 },
  0x0D01: { name: 'Lighting Info Query',                                   perm: 'Q',     valueSize: 1 },
  0x0D02: { name: 'Lighting Info',                                         perm: 'W/N' },
  0x0D03: { name: 'Lighting Info 2 Query',                                 perm: 'Q',     valueSize: 1 },
  0x0D04: { name: 'Lighting Info 2',                                       perm: 'W/N' },
  0x0D40: { name: 'Lighting Effect ID',                                    perm: 'R/W',   valueSize: 1 },
  0x0D41: { name: 'Lighting Brightness',                                   perm: 'R/W',   valueSize: 1 },
  0x0D42: { name: 'Lighting Temperature',                                  perm: 'R/W',   valueSize: 1 },
  0x0D43: { name: 'Lighting Speed',                                        perm: 'R/W',   valueSize: 1 },
  0x0D44: { name: 'Lighting Effect List for Shuffle',                      perm: 'R/W',   maxSize: 32 },
  0x0D45: { name: 'BassBoost Light State',                                 perm: 'R/W',   valueSize: 1 },
  0x0D46: { name: 'Lighting Color ID',                                     perm: 'R/W',   valueSize: 1 },
  0x0D47: { name: 'Lighting Custom Color',                                 perm: 'R/W',   valueSize: 3 },
  0x0D48: { name: 'Lighting Loop Info',                                    perm: 'R/W',   valueSize: 1 },
  0x0D4B: { name: 'Lighting Group ID List',                                perm: 'R/W' },
  0x0D49: { name: 'Lighting Group ID',                                     perm: 'R/W',   valueSize: 1 },
  0x0D4A: { name: 'Lighting Effect Info List',                             perm: 'R' },
  0x0D60: { name: 'Lighting Effect Reset',                                 perm: 'W',     valueSize: 0 },
  0x0D61: { name: 'Lighting Sunset Mode',                                  perm: 'R/W',   valueSize: 5 },
  0x0D62: { name: 'Charging Light State',                                  perm: 'R/W',   valueSize: 1 },
  0x0D80: { name: 'RGB Color Looping',                                     perm: 'R/W',   valueSize: 5 },
  // ── Gesture Group [0x0F00, 0x0FFF] ─────────────────────────────────────────
  0x0F00: { name: 'Left Swipe Forward',                                    perm: 'R/W',   valueSize: 1 },
  0x0F01: { name: 'Left Swipe Backward',                                   perm: 'R/W',   valueSize: 1 },
  0x0F02: { name: 'Right Swipe Forward',                                   perm: 'R/W',   valueSize: 1 },
  0x0F03: { name: 'Right Swipe Backward',                                  perm: 'R/W',   valueSize: 1 },
  0x0F04: { name: 'Left Tap',                                              perm: 'R/W',   valueSize: 1 },
  0x0F05: { name: 'Left Double Tap',                                       perm: 'R/W',   valueSize: 1 },
  0x0F06: { name: 'Left Triple Tap',                                       perm: 'R/W',   valueSize: 1 },
  0x0F07: { name: 'Right Tap',                                             perm: 'R/W',   valueSize: 1 },
  0x0F08: { name: 'Right Double Tap',                                      perm: 'R/W',   valueSize: 1 },
  0x0F09: { name: 'Right Triple Tap',                                      perm: 'R/W',   valueSize: 1 },
  0x0F0A: { name: 'Left Tap & Hold',                                       perm: 'R/W',   valueSize: 1 },
  0x0F0B: { name: 'Left Double Tap & Hold',                                perm: 'R/W',   valueSize: 1 },
  0x0F0C: { name: 'Right Tap & Hold',                                      perm: 'R/W',   valueSize: 1 },
  0x0F0D: { name: 'Right Double Tap & Hold',                               perm: 'R/W',   valueSize: 1 },
  0x0F80: { name: 'Dial 1',                                                perm: 'R/W',   valueSize: 1 },
  0x0F81: { name: 'Dial 2',                                                perm: 'R/W',   valueSize: 1 },
  0x0F82: { name: 'Button 1 Short Press',                                  perm: 'R/W',   valueSize: 1 },
  0x0F83: { name: 'Button 1 Long Press',                                   perm: 'R/W',   valueSize: 1 },
  0x0F84: { name: 'Button 1 Double Short Press',                           perm: 'R/W',   valueSize: 1 },
  0x0F85: { name: 'Button 2 Short Press',                                  perm: 'R/W',   valueSize: 1 },
  0x0F86: { name: 'Button 2 Long Press',                                   perm: 'R/W',   valueSize: 1 },
  0x0F87: { name: 'Button 2 Double Short Press',                           perm: 'R/W',   valueSize: 1 },
  0x0F88: { name: 'Button 1 Triple Short Press',                           perm: 'R/W',   valueSize: 1 },
  0x0F89: { name: 'Button 2 Triple Short Press',                           perm: 'R/W',   valueSize: 1 },
  0x0F90: { name: 'Base Station Rotate',                                   perm: 'R/W',   valueSize: 1 },
  0x0F91: { name: 'Base Station Short Press',                              perm: 'R/W',   valueSize: 1 },
  0x0F92: { name: 'Base Station Long Press',                               perm: 'R/W',   valueSize: 1 },
  0x0F93: { name: 'Base Station Press & Rotate',                           perm: 'R/W',   valueSize: 1 },
  0x0F94: { name: 'Base Station Sequential Feature List',                  perm: 'R/W' },
  0x0F95: { name: 'Base Station EQ Preset Selection',                      perm: 'R/W',   valueSize: 2 },
  0x0F96: { name: 'Base Station Mic Volume',                               perm: 'R/W',   valueSize: 2 },
  0x0FA0: { name: 'Base Station Operation',                                perm: '-',     valueSize: 2 },
  0x0FC0: { name: 'Gesture Accidental Touch Prevention',                   perm: 'R/W',   valueSize: 1 },
  // ── Headphone Misc Group [0x1000, 0x1CFF] ──────────────────────────────────
  0x1000: { name: 'TWS Info',                                              perm: 'R',     valueSize: 1 },
  0x1002: { name: 'In Ear Status',                                         perm: 'R',     valueSize: 1 },
  0x1003: { name: 'Sealing Test',                                          perm: 'W',     valueSize: 1 },
  0x1004: { name: 'Environment Noise Check',                               perm: 'R',     valueSize: 1 },
  0x1005: { name: 'Ear Tips',                                              perm: 'R/W',   valueSize: 1 },
  0x1006: { name: 'Enhance Volume',                                        perm: 'W',     valueSize: 7 },
  0x1008: { name: 'Total Playback Time',                                   perm: 'R',     valueSize: 4 },
  0x1009: { name: 'Total Power on Time',                                   perm: 'R',     valueSize: 4 },
  0x100A: { name: 'Find My Buds Status',                                   perm: 'R/W',   valueSize: 1 },
  0x100B: { name: 'Call Status',                                           perm: 'R',     valueSize: 1 },
  0x100C: { name: 'Auto Pickup Call',                                      perm: 'R/W',   valueSize: 1 },
  0x100D: { name: 'Private Call Mode',                                     perm: 'R/W',   valueSize: 2 },
  0x100E: { name: 'Dongle Firmware Version',                               perm: 'R',     valueSize: 3 },
  0x100F: { name: 'Smart Switch (Smart Audio & Video)',                    perm: 'R/W',   valueSize: 8 },
  0x1010: { name: 'Call Control',                                          perm: 'R/W',   valueSize: 1 },
  0x1011: { name: 'Call Volume Setting',                                   perm: 'R/W',   valueSize: 1 },
  0x1012: { name: 'Call Phone Name',                                       perm: 'R' },
  0x1013: { name: 'Call Phone Number',                                     perm: 'R' },
  0x1014: { name: 'Call Duration',                                         perm: 'R',     valueSize: 4 },
  0x1015: { name: 'Call Beam Forming',                                     perm: 'R/W',   valueSize: 1 },
  // ── Head Tracking Group [0x1D00, 0x1D3F] ───────────────────────────────────
  0x1D00: { name: 'Head Tracking Calibration Start / Stop',                perm: 'W',     valueSize: 1 },
  0x1D01: { name: 'Head Tracking Calibration Look Straight Ahead',         perm: 'W',     valueSize: 1 },
  0x1D02: { name: 'Head Tracking Calibration Look Down',                   perm: 'W',     valueSize: 1 },
  0x1D03: { name: 'Head Tracking Data',                                    perm: '-',     valueSize: 20 },
  0x1D04: { name: 'Microphone Calibration Mode',                           perm: 'W',     valueSize: 1 },
  // ── Personi-Fi Group [0x1E00, 0x1E3F] ──────────────────────────────────────
  0x1E00: { name: 'Personi-Fi Mode',                                       perm: 'R/W',   valueSize: 1 },
  0x1E01: { name: 'Hearing Test Mode',                                     perm: 'R/W',   valueSize: 1 },
  0x1E02: { name: 'Personi-Fi Setup Flow',                                 perm: 'W',     valueSize: 1 },
  0x1E03: { name: 'Hearing Test File Side',                                perm: 'W',     valueSize: 1 },
  0x1E04: { name: 'Hearing Test File Frequency',                           perm: 'R/W',   valueSize: 4 },
  // ── Safe Listening Group [0x1E80, 0x1EBF] ──────────────────────────────────
  0x1E80: { name: 'Safe Listening Current Volume',                         perm: 'R/W',   valueSize: 1 },
  0x1E81: { name: 'Safe Listening Max Volume Limit',                       perm: 'R/W',   valueSize: 1 },
  0x1E82: { name: 'Safe Listening Daily Time Limit',                       perm: 'R/W',   valueSize: 3 },
  0x1E83: { name: 'Safe Listening Today Listened Time',                    perm: 'R',     valueSize: 2 },
  0x1E84: { name: 'Safe Listening Pin Code',                               perm: 'R/W',   valueSize: 6 },
  0x1E85: { name: 'Safe Listening Average Volume History',                 perm: 'R' },
  0x1E86: { name: 'Safe Listening Daily Listened Time History',            perm: 'R' },
  0x1E87: { name: 'Safe Listening Remind Voice',                           perm: 'R/W',   valueSize: 1 },
  0x1E88: { name: 'Safe Listening Remind Voice Delete',                    perm: 'W',     valueSize: 1 },
  0x1E89: { name: 'Safe Listening Prepare Record & Play Voice',            perm: 'W',     valueSize: 1 },
  0x1E8A: { name: 'Safe Listening Prepare Record & Play Voice Status',     perm: '-',     valueSize: 1 },
  0x1E8B: { name: "Safe Listening Time's Up Status",                       perm: 'R',     valueSize: 1 },
  // ── Case Group [0x1F00, 0x1FFF] ─────────────────────────────────────────────
  0x1F00: { name: 'Launch OTA Mode',                                       perm: 'W',     valueSize: 1 },
  0x1F01: { name: 'Case Firmware Version',                                 perm: 'R',     valueSize: 3 },
  0x1F02: { name: 'Case MAC Address',                                      perm: 'R',     valueSize: 6 },
  0x1F03: { name: 'Case Battery Status',                                   perm: 'R',     valueSize: 1 },
  0x1F04: { name: 'Case Screen Brightness',                                perm: 'R/W',   valueSize: 1 },
  0x1F05: { name: 'Case Message Notification',                             perm: 'R/W',   valueSize: 1 },
  0x1F06: { name: 'Case Active Screen Saver Index',                        perm: 'R/W',   valueSize: 1 },
  0x1F07: { name: 'Case Screen Saver Time',                                perm: 'R/W',   valueSize: 2 },
  0x1F08: { name: 'Case Message Preview',                                  perm: 'R/W',   valueSize: 1 },
  0x1F09: { name: 'Case Customize Screen Saver CRC32',                     perm: 'R',     valueSize: 4 },
  0x1F0A: { name: 'Case Language',                                         perm: 'R',     valueSize: 1 },
  0x1F0B: { name: 'Case Unlock Indicator',                                 perm: 'R',     valueSize: 1 },
  0x1F0C: { name: 'Case Tab to Wake',                                      perm: 'R',     valueSize: 1 },
  0x1F0D: { name: 'Earbuds Latest Online Version',                         perm: 'R/W',   valueSize: 3 },
  0x1F0E: { name: 'Case Latest Online Version',                            perm: 'R/W',   valueSize: 3 },
  0x1F0F: { name: 'Case Find My Case',                                     perm: 'R',     valueSize: 1 },
  0x1F10: { name: 'Case Screen Size',                                      perm: 'R/W',   valueSize: 4 },
  0x1F11: { name: 'Case 24 Hour Time',                                     perm: 'R/W',   valueSize: 1 },
  0x1F12: { name: 'Case Custom Screen Saver Status',                       perm: 'R',     valueSize: 1 },
  0x1F13: { name: 'Case Custom Screen Saver Remove',                       perm: 'W',     valueSize: 1 },
  0x1F14: { name: 'Case Screen Saver Information',                         perm: 'R/W',   valueSize: 1 },
  0x1F15: { name: 'Case Screen Saver Information Opacity',                 perm: 'R/W',   valueSize: 1 },
  0x1F16: { name: 'Case Screen Saver Color Theme',                         perm: 'R/W',   valueSize: 3 },
  0x1F17: { name: 'Case Screen Saver Picture Opacity',                     perm: 'R/W',   valueSize: 1 },
  0x1F18: { name: 'Case Screen Saver Index List',                          perm: 'R' },
  0x1F80: { name: 'Case Earbud Charging Animation Config',                 perm: 'R/W' },
  0x1F81: { name: 'Case Earbud Low Battery Animation Config',              perm: 'R/W' },
  0x1F82: { name: 'Case Earbud Full Charge Animation Config',              perm: 'R/W' },
  0x1F83: { name: 'Case Power On Animation Config',                        perm: 'R/W' },
  0x1F84: { name: 'Case Screensaver Config',                               perm: 'R/W' },
  0x1F85: { name: 'Case Battery Level Page Config',                        perm: 'R/W' },
  0x1F86: { name: 'Case Message Notification Config',                      perm: 'R/W' },
  0x1F87: { name: 'Case Earbud Pairing Mode Config',                       perm: 'R/W' },
  0x1F88: { name: 'Case Earbud BT Connected Config',                       perm: 'R/W' },
  0x1F89: { name: 'Case Earbud BT Disconnected Config',                    perm: 'R/W' },
  0x1F8A: { name: 'Case Earbud In Ear Config',                             perm: 'R/W' },
  0x1F8B: { name: 'Case Earbud Out Ear Config',                            perm: 'R/W' },
  0x1F8C: { name: 'Case Earbud OTA Config',                                perm: 'R/W' },
  0x1F8D: { name: 'Case Error Config',                                     perm: 'R/W' },
  0x1F8E: { name: 'Case Find My Earbud Config',                            perm: 'R/W' },
  0x1F8F: { name: 'Case Earbud ANC Animation Config',                      perm: 'R/W' },
  0x1F90: { name: 'Case Earbud EQ Animation Config',                       perm: 'R/W' },
  0x1F91: { name: 'Case Earbud Media Play Animation Config',               perm: 'R/W' },
  0x1F92: { name: 'Case Earbud Media Pause Animation Config',              perm: 'R/W' },
  0x1F93: { name: 'Case Earbud Volume Up Animation Config',                perm: 'R/W' },
  0x1F94: { name: 'Case Earbud Volume Down Animation Config',              perm: 'R/W' },
  0x1F95: { name: 'Case Earbud Call Answer Animation Config',              perm: 'R/W' },
  0x1F96: { name: 'Case Earbud Call Hang Up Animation Config',             perm: 'R/W' },
  0x1F97: { name: 'Case Earbud Call Reject Animation Config',              perm: 'R/W' },
  0x1F98: { name: 'Case Earbud Voice Assistant Animation Config',          perm: 'R/W' },
  0x1F99: { name: 'Case Earbud Low Battery Warning Animation Config',      perm: 'R/W' },
  0x1F9A: { name: 'Case Custom Screen Saver Config',                       perm: 'R/W' },
  0x1F9B: { name: 'Case Full Charge Animation Config',                     perm: 'R/W' },
  0x1F9C: { name: 'Case Welcome Page Config',                              perm: 'R/W' },
  0x1F9D: { name: 'Case Time Page Config',                                 perm: 'R/W' },
  0x1F9E: { name: 'Case Earbud Name Page Config',                          perm: 'R/W' },
  0x1F9F: { name: 'Case BT Connection Info Config',                        perm: 'R/W' },
  0x1FA0: { name: 'Case Power Off Animation Config',                       perm: 'R/W' },
  0x1FA1: { name: 'Case Earbud Charging Complete Animation Config',        perm: 'R/W' },
  0x1FA2: { name: 'Case Ring Earbud Config',                               perm: 'R/W' },
  0x1FA3: { name: 'Case Earbud Sports Mode Animation Config',              perm: 'R/W' },
  0x1FA4: { name: 'Case Power Off Page Config',                            perm: 'R/W' },
  // ── Portable Misc Group [0x2000, 0x2AFF] ───────────────────────────────────
  0x2C00: { name: 'Party Status',                                          perm: 'R/W',   valueSize: 1 },
  0x2C01: { name: 'Party Group Type',                                      perm: 'R/W',   valueSize: 1 },
  0x2C02: { name: 'TWS Stereo Connection Status',                          perm: 'R/N',   valueSize: 1 },
  0x2C03: { name: 'Party Role',                                            perm: 'R/W',   valueSize: 1 },
  0x2C04: { name: 'Party Channel Type',                                    perm: 'R/W',   valueSize: 1 },
  0x2C05: { name: 'Party Group Name',                                      perm: 'R/W' },
  0x2C06: { name: 'Party Group ID',                                        perm: 'R/W',   valueSize: 4 },
  0x2C07: { name: 'Party Group Action',                                    perm: 'W',     valueSize: 1 },
  0x2C80: { name: 'Long Lasting Stereo Connection Status',                 perm: 'R/N',   valueSize: 1 },
  0x2C81: { name: 'Long Lasting Stereo Partner BT MAC Address',            perm: 'R',     valueSize: 6 },
  0x2C82: { name: 'Long Lasting Stereo Timeout',                           perm: 'R/W',   valueSize: 1 },
  // ── Audio Group [0x2D40, 0x2D7F] ───────────────────────────────────────────
  0x2D40: { name: 'Audio Operation',                                       perm: 'W',     valueSize: 1 },
  0x2D41: { name: 'Audio Mute Status',                                     perm: 'R/W',   valueSize: 1 },
  0x2D42: { name: 'Audio Volume',                                          perm: 'R/W',   valueSize: 1 },
  0x2D43: { name: 'Song Name',                                             perm: 'R' },
  0x2D44: { name: 'Artist Name',                                           perm: 'R' },
  0x2D45: { name: 'Song Lyric',                                            perm: 'W' },
  0x2D46: { name: 'Audio Codec Setting',                                   perm: 'R/W',   valueSize: 1 },
  0x2D60: { name: 'Current FM Radio Station Frequency',                    perm: 'R/W',   valueSize: 4 },
  0x2D61: { name: 'Current DAB Radio Station ID',                          perm: 'R/W',   valueSize: 4 },
  0x2D62: { name: 'Current Station Name',                                  perm: 'R' },
  // ── DJ Effect Group [0x2D80, 0x2DAF] ───────────────────────────────────────
  0x2D80: { name: 'DJ Effect Button 1',                                    perm: 'R/W',   valueSize: 1 },
  0x2D81: { name: 'DJ Effect Button 2',                                    perm: 'R/W',   valueSize: 1 },
  0x2D82: { name: 'DJ Effect Button 3',                                    perm: 'R/W',   valueSize: 1 },
  0x2D83: { name: 'DJ Effect Tone',                                        perm: 'R/W',   valueSize: 1 },
  0x2D84: { name: 'DJ Effect Voice',                                       perm: 'R/W',   valueSize: 1 },
  0x2D85: { name: 'DJ Filter Name',                                        perm: 'R/W',   valueSize: 1 },
  0x2D86: { name: 'DJ Filter',                                             perm: 'R/W',   valueSize: 1 },
  // ── Radio Group [0x2DB0, 0x2DFF] ───────────────────────────────────────────
  0x2DB0: { name: 'Radio Scan',                                            perm: 'W',     valueSize: 2 },
  0x2DB1: { name: 'Radio Info',                                            perm: '-' },
  0x2DB2: { name: 'Radio Station Update',                                  perm: 'W',     valueSize: 6 },
  0x2DB3: { name: 'Radio Station Update Preset Index',                     perm: 'W',     valueSize: 6 },
  // ── Karaoke Group [0x2D00, 0x2D3F] ────────────────────────────────────────
  0x2D00: { name: 'Karaoke Bass',                                          perm: 'R/W',   valueSize: 1 },
  0x2D01: { name: 'Karaoke Treble',                                        perm: 'R/W',   valueSize: 1 },
  0x2D02: { name: 'Karaoke Echo',                                          perm: 'R/W',   valueSize: 1 },
  0x2004: { name: 'Auracast Mode',                                         perm: 'R/W',   valueSize: 1 },
  0x2005: { name: 'Harman Auracast Standard Quality',                      perm: 'R/W',   valueSize: 1 },
  0x2006: { name: 'Playtime Boost',                                        perm: 'R/W',   valueSize: 1 },
  0x2007: { name: 'Mood Sound',                                            perm: 'R/W',   valueSize: 1 },
  0x2008: { name: 'Power On/Off Sync',                                     perm: 'R/W',   valueSize: 1 },
  0x2009: { name: 'Bass Boost',                                            perm: 'R/W',   valueSize: 1 },
  0x200A: { name: 'USB Status',                                            perm: 'R/N',   valueSize: 1 },
  0x200B: { name: 'AI Vocal Removal',                                      perm: 'R/W',   valueSize: 1 },
  0x200C: { name: 'Guitar Volume',                                         perm: 'R/W',   valueSize: 1 },
  0x200D: { name: 'Speaker Volume Sync Status',                            perm: 'R',     valueSize: 1 },
  0x200E: { name: 'User EQ Status',                                        perm: 'R',     valueSize: 1 },
  0x2011: { name: 'Identify Device',                                       perm: 'R/W',   valueSize: 1 },
  0x2012: { name: 'Knob Menu Reset Time',                                  perm: 'R/W',   valueSize: 1 },
  0x2013: { name: 'Hotel Mode Status',                                     perm: 'R/W',   valueSize: 1 },
  0x2014: { name: 'Top Panel Lock',                                        perm: 'R/W',   valueSize: 1 },
  0x2015: { name: 'USB-C Port Working Mode',                               perm: 'R/W',   valueSize: 1 },
  0x200F: { name: 'Feedback Tone Status',                                  perm: 'R/W',   valueSize: 1 },
  0x2010: { name: 'Cross Platform TWS Status',                             perm: 'R/W',   valueSize: 1 },
  // ── Bluetooth Assistant Group [0x2B00, 0x2BFF] ─────────────────────────────
  0x2B00: { name: 'BT Assistant Status',                                   perm: 'R/W',   valueSize: 1 },
  0x2B01: { name: 'BT Assistant Type',                                     perm: 'R/W',   valueSize: 1 },
  // ── Party Group [0x2C00, 0x2CFF] ───────────────────────────────────────────
  0x2E00: { name: 'Battery ID',                                            perm: 'R',     maxSize: 16 },
  0x2E01: { name: 'Battery Remaining Playtime',                            perm: 'R',     valueSize: 2 },
  0x2E02: { name: 'Battery Temperature Max',                               perm: 'R',     valueSize: 2 },
  0x2E03: { name: 'Battery Remaining Capacity',                            perm: 'R',     valueSize: 2 },
  0x2E04: { name: 'Battery Full Charge Capacity',                          perm: 'R',     valueSize: 2 },
  0x2E05: { name: 'Battery Design Capacity',                               perm: 'R',     valueSize: 2 },
  0x2E06: { name: 'Battery Charge Cycle Count',                            perm: 'R',     valueSize: 2 },
  0x2E07: { name: 'Battery State of Health',                               perm: 'R',     valueSize: 1 },
  0x2E08: { name: 'Battery Charging Status',                               perm: 'R',     valueSize: 1 },
  0x2E09: { name: 'Battery Health Notification',                           perm: 'R',     valueSize: 1 },
  0x2E0A: { name: 'Battery Total Power on Duration',                       perm: 'R',     valueSize: 4 },
  0x2E0B: { name: 'Battery Total Playback Time Duration',                  perm: 'R',     valueSize: 4 },
  // ── Party Light Group [0x2F00, 0x2FFF] ─────────────────────────────────────
  0x2F00: { name: 'Party Light Stage Support Status',                      perm: 'R',     valueSize: 1 },
  0x2F01: { name: 'Party Light Stage Action Type',                         perm: 'R',     valueSize: 1 },
  0x2F02: { name: 'Party Light Stage Group Device Count',                  perm: 'R',     valueSize: 1 },
  0x2F03: { name: 'Party Light Sound Detection',                           perm: 'R/W',   valueSize: 1 },
  0x2F04: { name: 'Party Light Boost Light Up',                            perm: 'R/W',   valueSize: 1 },
  0x2F05: { name: 'Party Light Battery Saving Mode Status',                perm: 'R',     valueSize: 1 },
  0x2F06: { name: 'Party Light Battery Saving Mode',                       perm: 'R',     valueSize: 1 },
  0x2F07: { name: 'Party Light Brightness',                                perm: 'R/W',   valueSize: 1 },
  0x2F08: { name: 'Party Light LED Movement Speed',                        perm: 'R/W',   valueSize: 1 },
  0x2F09: { name: 'Assign Party Box to Party Light',                       perm: 'R/W',   valueSize: 1 },
  0x2F0A: { name: 'Stage Light Number',                                    perm: 'R/W',   valueSize: 1 },
  // ── BandBox Group [0x3000, 0x3FFF] ─────────────────────────────────────────
  0x3000: { name: 'Hifi Drum Start / Stop',                                perm: 'R/W',   valueSize: 1 },
  0x3001: { name: 'Hifi Drum Tempo',                                       perm: 'R/W',   valueSize: 2 },
  0x3002: { name: 'Hifi Drum Sequence',                                    perm: 'R/W',   valueSize: 1 },
  0x3003: { name: 'Hifi Drum Tap',                                         perm: '-',     valueSize: 4 },
  0x3040: { name: 'Hifi Metronome Start / Stop',                           perm: 'R/W',   valueSize: 1 },
  0x3041: { name: 'Hifi Metronome Tempo',                                  perm: 'R/W',   valueSize: 2 },
  0x3042: { name: 'Hifi Metronome Sequence',                               perm: 'R/W',   valueSize: 1 },
  0x3043: { name: 'Hifi Metronome Tap',                                    perm: '-',     valueSize: 4 },
  0x3080: { name: 'AI (Stem Separation) Karaoke Mode',                     perm: 'R/W',   valueSize: 1 },
  0x3081: { name: 'AI (Stem Separation) Track Type',                       perm: 'W',     valueSize: 1 },
  0x3082: { name: 'AI (Stem Separation) Track Volume',                     perm: 'W',     valueSize: 2 },
  0x3083: { name: 'AI (Stem Separation) Track Type Query',                 perm: 'W',     valueSize: 1 },
  0x3084: { name: 'AI (Stem Separation) Track Volume Query',               perm: 'W',     valueSize: 1 },
  0x3085: { name: 'AI (Stem Separation) Mode',                             perm: 'R/W',   valueSize: 1 },
  0x30C0: { name: 'Pitch Start / Stop',                                    perm: 'R/W',   valueSize: 1 },
  0x30C1: { name: 'Pitch Change',                                          perm: 'R/W',   valueSize: 2 },
  0x3100: { name: 'Hifi Tuner Start / Stop',                               perm: 'R/W',   valueSize: 1 },
  0x3101: { name: 'Hifi Tuner Mode',                                       perm: 'R/W',   valueSize: 1 },
  0x3102: { name: 'Hifi Tuner Bass Mode',                                  perm: 'R/W',   valueSize: 1 },
  0x3103: { name: 'Hifi Tuner Tempo',                                      perm: 'R/W',   valueSize: 2 },
  0x3104: { name: 'Hifi Tuner String',                                     perm: 'R/W',   valueSize: 1 },
  0x3106: { name: 'Hifi Tuner Result',                                     perm: '-',     valueSize: 4 },
  0x3107: { name: 'Hifi Tuner Chromatic Tuning Status',                    perm: 'R/W',   valueSize: 1 },
  0x3108: { name: 'Hifi Tuner Chromatic Tuning Result',                    perm: '-',     valueSize: 4 },
  0x3140: { name: 'Looper Recording Operation',                            perm: 'R/W',   valueSize: 1 },
  0x3141: { name: 'Looper Music Signal Report Interval',                   perm: 'R/W',   valueSize: 2 },
  0x3142: { name: 'Looper Music Signal',                                   perm: '-',     valueSize: 2 },
  0x3143: { name: 'Looper Record Time Duration',                           perm: 'R',     valueSize: 4 },
  0x3144: { name: 'Looper Audio Data Trimming',                            perm: 'W',     valueSize: 8 },
  0x3145: { name: 'Looper Record Play Operation',                          perm: 'R/W',   valueSize: 1 },
  0x3146: { name: 'Looper Record Play Timestamp',                          perm: 'R/W',   valueSize: 4 },
  0x3147: { name: 'Looper Number of Bars',                                 perm: 'R/W',   valueSize: 1 },
  0x3148: { name: 'Looper Layer Count',                                    perm: 'R',     valueSize: 1 },
  0x3149: { name: 'Looper Record Count Down',                              perm: '-',     valueSize: 4 },
  0x314A: { name: 'Looper Record Estimated Time Duration',                 perm: 'R',     valueSize: 4 },
  0x314B: { name: 'Looper Record Time Left',                               perm: 'R',     valueSize: 4 },
  0x3180: { name: 'Output Record Storage Location',                        perm: 'R/W',   valueSize: 1 },
  0x3181: { name: 'Output Recording Start / Stop',                         perm: 'R/W',   valueSize: 1 },
  0x3182: { name: 'Output Separate Tracks Enable / Disable',               perm: 'R/W',   valueSize: 1 },
  0x3183: { name: 'Output Record File Name',                               perm: 'R/W' },
  0x3184: { name: 'Output Record File Name List',                          perm: 'R' },
  0x3185: { name: 'Output Record File Operate',                            perm: 'R/W',   valueSize: 1 },
  0x3186: { name: 'Output Record File Path',                               perm: '-' },
  0x31C0: { name: 'Primary Control EQ Info Query',                         perm: 'W' },
  0x31C1: { name: 'Primary Control EQ Info',                               perm: 'W' },
  0x31C2: { name: 'Mic & Keyboard EQ Info Query',                          perm: 'W' },
  0x31C3: { name: 'Mic & Keyboard EQ Info',                                perm: 'W' },
  0x3400: { name: 'Channel Input Status Query',                            perm: 'W',     valueSize: 1 },
  0x3401: { name: 'Channel Input Status',                                  perm: '-' },
  0x3402: { name: 'Guitar Pickup Query',                                   perm: 'W',     valueSize: 1 },
  0x3403: { name: 'Guitar Pickup',                                         perm: 'W',     valueSize: 2 },
  0x3404: { name: 'AUX Type',                                              perm: 'R/W',   valueSize: 1 },
  0x3405: { name: 'Channel Volume Level Query',                            perm: 'W',     valueSize: 1 },
  0x3406: { name: 'Channel Volume Level',                                  perm: 'W',     valueSize: 2 },
  0x3440: { name: 'Guitar Preset All Simple Info',                         perm: 'R' },
  0x3441: { name: 'Guitar Preset Select Query',                            perm: 'W',     valueSize: 1 },
  0x3442: { name: 'Guitar Preset Select',                                  perm: 'W',     valueSize: 2 },
  0x3443: { name: 'Guitar Preset Info Query',                              perm: 'W',     valueSize: 1 },
  0x3444: { name: 'Guitar Preset Info',                                    perm: '-' },
  0x3445: { name: 'Guitar Preset Slot Info',                               perm: 'W' },
  0x3446: { name: 'Guitar Preset Operation',                               perm: 'W' },
  0x3447: { name: 'Guitar Preset On-Product ID List',                      perm: 'R/W' },
  0x3448: { name: 'Guitar Preset My Favorite List Query',                  perm: 'W' },
  0x3449: { name: 'Guitar Preset My Favorite ID List',                     perm: 'W' },
  0x344A: { name: 'Guitar Preset Genre List',                              perm: 'R' },
  0x3800: { name: 'Prepare OTA Path',                                      perm: 'R/W',   valueSize: 1 },
  0x3801: { name: 'BandBox Device OOBE',                                   perm: 'R/W',   valueSize: 1 },
  0x3802: { name: 'Backward Screen',                                       perm: 'R/W',   valueSize: 1 },
  0x3803: { name: 'Page In Use Status Query',                              perm: 'W',     valueSize: 1 },
  0x3804: { name: 'Page In Use',                                           perm: 'W',     valueSize: 2 },
  0x3805: { name: 'BandBox Supported Feature List',                        perm: 'R' },
  0x3806: { name: 'Microphone Brand and Model Query',                      perm: 'W',     valueSize: 1 },
  0x3807: { name: 'Microphone Brand and Model',                            perm: 'W' },
  // ── Tuning Tool Group [0x4000, 0x4FFF] ─────────────────────────────────────
  0x4000: { name: 'Audio Input List',                                      perm: 'R' },
  0x4001: { name: 'Audio Input Info Query',                                perm: 'W',     valueSize: 1 },
  0x4002: { name: 'Audio Input Info',                                      perm: 'W' },
  0x4040: { name: 'Audio Output Total Channel Number',                     perm: 'R/W',   valueSize: 1 },
  0x4041: { name: 'Audio Output Channel Info List',                        perm: 'R' },
  0x4042: { name: 'Audio Output Channel Info Query',                       perm: 'W',     valueSize: 1 },
  0x4043: { name: 'Audio Output Channel Volume in dB',                     perm: 'W' },
  0x4044: { name: 'Audio Output Channel Delay',                            perm: 'W' },
  0x4045: { name: 'Audio Output Channel Phase',                            perm: 'W' },
  0x4046: { name: 'Audio Output Channel HPF',                              perm: 'W' },
  0x4047: { name: 'Audio Output Channel LPF',                              perm: 'W' },
  0x4048: { name: 'Audio Output Channel Compressor',                       perm: 'W' },
  0x4049: { name: 'Audio Output Channel EQ',                               perm: 'W' },
  0x404A: { name: 'Audio Output Channel Reset',                            perm: 'W',     valueSize: 1 },
  0x4080: { name: 'Audio Input Mixer List',                                perm: 'R' },
  0x4081: { name: 'Audio Input Mixer Query',                               perm: 'W',     valueSize: 1 },
  0x4082: { name: 'Audio Input Mixer',                                     perm: 'W' },
  0x40C0: { name: 'Amplifier Node List',                                   perm: 'R' },
  0x40C1: { name: 'Audio Output and Amplifier Channel Mapping Query',      perm: 'W',     valueSize: 1 },
  0x40C2: { name: 'Audio Output and Amplifier Channel Mapping',            perm: 'W' },
  0x4100: { name: 'Main Volume in dB',                                     perm: 'R/W',   valueSize: 4 },
  0x4101: { name: 'Main Volume Reset',                                     perm: 'W',     valueSize: 0 },
  0x4140: { name: 'Noise Gate',                                            perm: 'R/W' },
  0x4141: { name: 'Noise Gate Reset',                                      perm: 'W',     valueSize: 0 },
  0x4180: { name: 'Limiter',                                               perm: 'R/W' },
  0x4181: { name: 'Limiter Reset',                                         perm: 'W',     valueSize: 0 },
  0x41C0: { name: 'All Scenarios Raw Data',                                perm: 'R/W' },
  0x41C1: { name: 'Get Current Scenario Item Info',                        perm: 'R' },
  0x41C2: { name: 'Get Scenario List',                                     perm: 'R' },
  0x41C3: { name: 'Scenario Operation',                                    perm: 'W' },
  0x41C4: { name: 'Rename Scenario',                                       perm: 'W' },
}

// Feature group ranges
export const FEATURE_GROUP_RANGES = [
  { name: 'Common',                start: 0x0000, end: 0x0AFF },
  { name: 'OTA',                   start: 0x0B00, end: 0x0B3F },
  { name: 'AI',                    start: 0x0B40, end: 0x0B7F },
  { name: 'LE Audio',              start: 0x0B80, end: 0x0BBF },
  { name: 'Mic',                   start: 0x0C00, end: 0x0C3F },
  { name: 'Voice Prompt',          start: 0x0C40, end: 0x0C7F },
  { name: 'PSAP',                  start: 0x0C80, end: 0x0CAF },
  { name: 'Sleep',                 start: 0x0CB0, end: 0x0CFF },
  { name: 'Lighting',              start: 0x0D00, end: 0x0DFF },
  { name: 'EQ',                    start: 0x0E00, end: 0x0EFF },
  { name: 'Gesture',               start: 0x0F00, end: 0x0FFF },
  { name: 'Headphone Misc',        start: 0x1000, end: 0x1CFF },
  { name: 'Head Tracking',         start: 0x1D00, end: 0x1D3F },
  { name: 'Personi-Fi',            start: 0x1E00, end: 0x1E3F },
  { name: 'Safe Listening',        start: 0x1E80, end: 0x1EBF },
  { name: 'Case',                  start: 0x1F00, end: 0x1FFF },
  { name: 'Portable Misc',         start: 0x2000, end: 0x2AFF },
  { name: 'Bluetooth Assistant',   start: 0x2B00, end: 0x2BFF },
  { name: 'Party',                 start: 0x2C00, end: 0x2CFF },
  { name: 'Karaoke',               start: 0x2D00, end: 0x2D3F },
  { name: 'Audio',                 start: 0x2D40, end: 0x2D7F },
  { name: 'DJ Effect',             start: 0x2D80, end: 0x2DAF },
  { name: 'Radio',                 start: 0x2DB0, end: 0x2DFF },
  { name: 'Battery',               start: 0x2E00, end: 0x2EFF },
  { name: 'Party Light',           start: 0x2F00, end: 0x2FFF },
  { name: 'BandBox',               start: 0x3000, end: 0x3FFF },
  { name: 'Tunning Tool',          start: 0x4000, end: 0x4FFF },
]

export function getFeatureGroup(featureId) {
  for (const g of FEATURE_GROUP_RANGES) {
    if (featureId >= g.start && featureId <= g.end) return g.name
  }
  return 'Unknown'
}

// Merge bit-field descriptions from feature-fields.js into FEATURE_ID_MAP.
// To add or update descriptions, edit src/utils/feature-fields.js only.
Object.entries(FEATURE_FIELDS).forEach(([id, fields]) => {
  const entry = FEATURE_ID_MAP[Number(id)]
  if (entry) entry.fields = fields
})

// Color ID table
export const COLOR_ID_MAP = {
  0x00: 'Black',         0x01: 'White',           0x02: 'Blue',            0x03: 'Red',
  0x04: 'Green',         0x05: 'Purple',          0x06: 'Gold Silver',     0x07: 'Silver',
  0x08: 'Grey',          0x09: 'Beige',           0x0A: 'Pink',            0x0B: 'Chrome',
  0x0C: 'Rose Gold',     0x0D: 'Coral',           0x0E: 'Ghost Black',     0x0F: 'Ghost Purple',
  0x10: 'Ghost White',   0x11: 'Mint',            0x12: 'Black TomorrowLand', 0x13: 'Champaign Gold',
  0x14: 'Brown',         0x15: 'Square Black',    0x16: 'Square White',    0x17: 'Square Brown',
  0x18: 'Yellow',        0x19: 'Rose',            0x1A: 'Squad (Camo)',    0x1B: 'Turquoise',
  0x1C: 'Peach Orange',  0x1D: 'Black Gray',      0x1E: 'Black Lime',      0x1F: 'Orange',
  0x20: 'Copper',        0x21: 'Cyan',            0x22: 'Red Blue',        0x23: 'Blue Green',
  0x24: 'Blue Pink',     0x25: 'Teal',            0x26: 'Gun Metal',       0x27: 'Lime',
}

// Audio Source table
export const AUDIO_SOURCE_MAP = {
  0x00: 'None',       0x01: 'BT',         0x02: 'AUX',          0x03: 'USB Flash Disk',
  0x04: 'Optical',    0x05: 'FM Radio',   0x06: 'DAB Radio',    0x07: 'UAC',
  0x08: 'RCA',        0x09: 'A2B',        0x0A: 'Coaxial',      0x0B: '2.4G',
  0x0C: 'Looper',     0x0D: 'HDMI',       0x0E: 'PartyTogether',
}

// Host Type table
export const HOST_TYPE_MAP = {
  0x01: 'Android',  0x02: 'iOS',  0x03: 'Dongle',  0x04: 'Soundbar',
}

// Status code tables
export const PROTOCOL_STATUS_ID = {
  0x01: 'First Timeout',          0x02: 'Second Timeout',
  0x03: 'Packet Missing',         0x04: 'Unknown Identifier',
  0x05: 'Unsupported Version',    0x06: 'Unsupported Command ID',
  0x07: 'Wrong Packet Count',     0x08: 'Wrong Packet Index',
  0xFF: 'General Error',
}

export const BUSINESS_STATUS_ID = {
  0x01: 'Already In OTA',                  0x02: 'Battery Low',
  0x03: 'Busy In Call',                    0x04: 'Busy In Audio Streaming',
  0x05: 'Busy In AI',                      0x06: 'Signature Verification Failed',
  0x07: 'Wrong Password',                  0x08: 'Unsupported OTA Package Version',
  0x09: 'TWS In Mono Mode',               0x0E: 'Busy In Erasing',
  0x0F: 'Dongle and Headset Disconnected', 0xFF: 'General Error',
}

// BLE Legacy Service Data mask bit definitions (bit15 → bit0 order)
export const MASK_BIT_DEFS = [
  { bit: 15, name: 'colorId',           size: 1 },
  { bit: 14, name: 'srcName1CRC16',     size: 2 },
  { bit: 13, name: 'srcName2CRC16',     size: 2 },
  { bit: 12, name: 'btMacCRC16',        size: 2 },
  { bit: 11, name: 'macAddress',        size: 6 },
  { bit: 10, name: 'batteryInfo',       size: 1 },
  { bit: 9,  name: 'deviceMiscInfo',    size: 2 },
  { bit: 8,  name: 'partyMethodInfo',   size: 1 },
  { bit: 7,  name: 'partyInfo',         size: 2 },
  { bit: 6,  name: 'stereoGroupId',     size: 1 },
  { bit: 5,  name: 'firmwareVersion3B', size: 3 },
  { bit: 4,  name: 'deviceId',          size: 3 },
  { bit: 3,  name: 'partyLightInfo',    size: 2 },
  { bit: 2,  name: 'firmwareVersion5B', size: 5 },
  { bit: 1,  name: 'deviceMiscInfo2',   size: 2 },
  { bit: 0,  name: 'reserved',          size: 0 },
]

// Extended Service Data type definitions
export const SERVICE_DATA_TYPE_MAP = {
  0x01: { name: 'Color ID',               size: 1 },
  0x02: { name: 'SrcName1 CRC16',         size: 2 },
  0x03: { name: 'SrcName2 CRC16',         size: 2 },
  0x04: { name: 'BT MAC Address CRC16',   size: 2 },
  0x05: { name: 'BT MAC Address',         size: 6 },
  0x06: { name: 'Battery Level',          size: 1 },
  0x07: { name: 'Device Misc Info',       size: 2 },
  0x08: { name: 'Party Method Info',      size: 1 },
  0x09: { name: 'Party Info',             size: 2 },
  0x0A: { name: 'Stereo Group ID',        size: 1 },
  0x0B: { name: 'Firmware Version (3B)',  size: 3 },
  0x0C: { name: 'Device ID',              size: 3 },
  0x0D: { name: 'Party Light Info',       size: 2 },
  0x0E: { name: 'Firmware Version (5B)',  size: 5 },
  0x0F: { name: 'Device Misc Info 2',     size: 2 },
}

// Sample data — sourced from protocol spec v5.0.10 examples + hand-crafted verification cases
export const SAMPLE_DATA = [
  // ── 4.1.1 GET Command (p.17) ─────────────────────────────────────────────
  {
    label: 'GET Request — MTU + Product ID',
    hex: 'DD 00 01 00 01 00 04 00 01 00 04 00',
    desc: 'App → Device: Get featureId 0x0001 (MTU) and 0x0004 (Product ID). Payload = two 2-byte feature IDs.'
  },
  {
    label: 'GET Response — Product ID = 0x8001',
    hex: '00 DD 01 00 01 00 0C 00 00 00 04 00 02 00 01 80',
    desc: 'Device → App: status=0x0000, featureId=0x0004, valueSize=2, value=0x8001 (LE).'
  },
  // ── 4.1.2 SET Command (p.18) ─────────────────────────────────────────────
  {
    label: 'SET Request — ANC On',
    hex: 'DD 00 02 00 01 00 05 00 18 00 01 00 80',
    desc: 'App → Device: featureId=0x0018(ANC), valueSize=1, value=0x80 (bit7=1 On, level=0).'
  },
  {
    label: 'SET ACK — Success',
    hex: 'DD 00 02 00 01 00 02 00 00 00',
    desc: 'Device → App: SET ACK, statusCode=0x0000 (success).'
  },
  {
    label: 'SET ACK — General Error',
    hex: 'DD 00 02 00 01 00 02 00 FF 80',
    desc: 'Device → App: SET ACK, statusCode=0x80FF (error, protocol category, general error).'
  },
  // ── 4.1.3 Notification Device→App (p.19) ─────────────────────────────────
  {
    label: 'Notification — Battery 100%',
    hex: '00 DD 03 00 01 00 08 00 00 00 0D 00 01 00 64',
    desc: 'Device → App (0x0003): status=0x0000, featureId=0x000D, valueSize=1, value=0x64 (100%, not charging).'
  },
  {
    label: 'Notification — ANC Status',
    hex: '00 DD 03 00 01 00 08 00 00 00 18 00 01 00 80',
    desc: 'Device → App: status=0x0000, featureId=0x0018(ANC), valueSize=1, value=0x80 (On, level=0).'
  },
  {
    label: 'Notification — App→Device (0x0004)',
    hex: '00 DD 04 00 01 00 08 00 00 00 0D 00 01 00 40',
    desc: 'App → Device (0x0004): status=0x0000, featureId=0x000D, valueSize=1, value=0x40 (64%, not charging).'
  },
  // ── 4.1.4 Multi-packet Notification example (p.20) ───────────────────────
  // Packet 1: status + Feature1(size=2,val=AABB) + Feature2 header + first 108 bytes of value
  // Feature2 valueSize=228(0x00E4); total payload1 = 2+2+2+2+2+2+108 = 120 bytes
  {
    label: 'Multi-packet Notification — Packet 1/2',
    hex: '00 DD 03 00 02 00 78 00'
       + ' 00 00'                     // status = success
       + ' 12 00 02 00 AB CD'          // featureId=0x0012(AutoPowerOff), size=2, val=0xCDAB (on, 11179s)
       + ' 3C 00 E4 00'               // featureId=0x003C(Full FW Version), size=228
       + ' 4D 61 69 6E 3A 31 2E 31 2E 30 2C 20 49 43 31 3A 31 2E 30 2E 31 2C 20 49 43 32 3A 31 2E 30 2E 32 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00',
    desc: 'Packet 1 of 2: packetCount=2, packetIndex=0. Contains AutoPowerOff feature + start of Full FW Version (108 of 228 bytes).'
  },
  {
    label: 'Multi-packet Notification — Packet 2/2',
    hex: '00 DD 03 00 02 01 78 00'
       + ' 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00',
    desc: 'Packet 2 of 2: packetCount=2, packetIndex=1. Continuation (remaining 120 bytes of Full FW Version value).'
  },
  // ── 4.2 OTA Commands (p.22–25) ───────────────────────────────────────────
  {
    label: 'Start OTA Request',
    hex: 'DD 00 01 01 01 00 00 00',
    desc: 'App → Device: commandId=0x0101(Start OTA), payloadLength=0, no payload.'
  },
  {
    label: 'Send OTA Data',
    hex: 'DD 00 02 01 01 00 08 00 00 00 00 00 DE AD BE EF',
    desc: 'App → Device: commandId=0x0102, absoluteOffset=0x00000000, OTA data=DE AD BE EF.'
  },
  {
    label: 'Stop OTA Request',
    hex: 'DD 00 03 01 01 00 00 00',
    desc: 'App → Device: commandId=0x0103(Stop OTA), payloadLength=0.'
  },
  {
    label: 'OTA Notification — 10.50% progress',
    hex: '00 DD 04 01 01 00 0C 00 00 00 1A 04 00 00 00 00 00 00 00 10',
    desc: 'Device → App: commandId=0x0104, status=0x0000, percentage=1050 (10.50%), absoluteOffset=0, lengthToRead=0x00100000.'
  },
  {
    label: 'OTA Notification — 100% complete',
    hex: '00 DD 04 01 01 00 0C 00 00 00 10 27 00 00 00 00 00 00 00 00',
    desc: 'Device → App: percentage=10000 (100.00%), lengthToRead=0 → all data received, device will reboot.'
  },
  {
    label: 'OTA Notification — First Timeout',
    hex: '00 DD 04 01 01 00 0C 00 01 81 00 00 00 00 00 00 00 00 00 00',
    desc: 'Device → App: statusCode=0x8101 (Protocol category, First Timeout).'
  },
  // ── 2.1.1 Legacy BLE Service Data (p.7) ──────────────────────────────────
  {
    label: 'BLE Legacy Service Data — ColorID + BT MAC CRC (Mask=0x9000)',
    hex: 'A3 20 00 90 08 AB CD',
    desc: 'PID=0x20A3, Mask=0x9000 (bit15=ColorID, bit12=BT MAC CRC16). Data: colorId=0x08(Grey), macCRC=0xCDAB.'
  },
  {
    label: 'BLE Legacy Service Data — ColorID + 2×SrcName CRC + BT MAC CRC (Mask=0xF000)',
    hex: 'A3 20 00 F0 08 12 34 56 78 AB CD',
    desc: 'PID=0x20A3, Mask=0xF000 (bit15..12). Data: colorId=0x08, srcName1CRC=0x3412, srcName2CRC=0x7856, macCRC=0xCDAB.'
  },
  // ── 2.1.2 Extended BLE Service Data (p.8) ────────────────────────────────
  {
    label: 'BLE Extended Service Data — ColorID + Battery',
    hex: 'A3 20 02 01 08 02 06 64',
    desc: 'PID=0x20A3. Entry1: len=2,type=0x01(ColorID),val=0x08(Grey). Entry2: len=2,type=0x06(Battery),val=0x64(100%,not charging).'
  },
  // ── BLE AD Structure wrapper (p.6) ───────────────────────────────────────
  {
    label: 'BLE AD Structure — Extended Service Data',
    hex: '09 16 DF FD A3 20 02 01 08 02 06 64',
    desc: 'AD length=9, type=0x16, UUID=0xFDDF(Harman). Service data: PID=0x20A3, ColorID=Grey, Battery=100%.'
  },
]
